-- The roll time limit: one test per row of the README's "Roll Time Limit"
-- table, plus the chat warning before time runs out. Times are read from the
-- addon (time_left) rather than hardcoded.
local loader = require("spec.support.loader")
local helpers = require("spec.support.helpers")

describe("the roll time limit", function()
	local game

	before_each(function()
		game = helpers.new(loader.load())
	end)

	-- Starts a round with every player, then has some of them roll.
	-- rolls: { "Name", roll, ... } for the players who roll
	local function play(mode, players, rolls)
		game:start_round({ mode = mode, bet = "500", players = players })
		for index = 1, #(rolls or {}), 2 do
			game:roll(rolls[index], rolls[index + 1])
		end
	end

	local function assert_cancelled()
		assert.is_true(game:chat_contains("Time's up! Not enough players rolled. Round cancelled."))
		assert.is_nil(game.host.game.data)
		assert.are.equal("NewGame", game:stage())
		assert.is_false(game:is_listening())
		assert.are.same({}, game:rankings())
	end

	describe("in the chat", function()
		it("warns who is still missing before time runs out", function()
			play("HiLo", { "Jayred", "Zed", "Piyu" }, { "Jayred", 400 })
			local mark = game:mark()
			local warning_in = game:time_until_warning()
			game:advance(warning_in - 0.1)
			assert.is_false(game:chat_contains("Still waiting on", mark))

			game:advance(0.1)
			assert.is_true(game:chat_contains(game:time_left() .. " seconds left! Still waiting on: Piyu, Zed", mark))
		end)

		it("gives every roll phase its own time limit", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" })
			game:advance(20)
			game:roll("Jayred", 400)
			game:roll("Piyu", 100)
			game:roll("Zed", 100) -- tie for last: a losers' tiebreaker starts now

			local limit = game:time_left()
			game:advance(limit - 1)
			assert.is_false(game:chat_contains("Time's up!"))
			game:advance(1)
			assert.is_true(game:chat_contains("Time's up!"))
		end)
	end)

	describe("in a normal round", function()
		it("removes players who didn't roll and scores the rest", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 400, "Piyu", 100 })
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Removed for not rolling: Zed"))
			assert.is_true(game:chat_contains("Piyu owes Jayred 300 gold!"))
			assert.is_nil(game:rankings().Zed)
		end)

		it("cancels the round when fewer than 2 players rolled", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 400 })
			game:wait_for_timeout()
			assert_cancelled()
		end)

		it("cancels the round when nobody rolled", function()
			play("HiLo", { "Jayred", "Piyu" })
			game:wait_for_timeout()
			assert_cancelled()
		end)

		it("removes players who didn't roll in the Blackjack deal too", function()
			play("Blackjack", { "Jayred", "Piyu", "Zed" }, { "Jayred", 15, "Piyu", 18 })
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Removed for not rolling: Zed"))
			assert.is_true(game:chat_contains(AG_MESSAGES.DEALT))

			game:say("Jayred", "stand")
			game:say("Piyu", "stand")
			assert.is_true(game:chat_contains("Jayred owes Piyu 500 gold!"))
		end)
	end)

	describe("in a losers' tiebreaker", function()
		it("makes the player who didn't roll lose", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 400, "Piyu", 100, "Zed", 100 })
			game:roll("Piyu", 300)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Zed didn't roll and loses the round."))
			assert.is_true(game:chat_contains("Zed owes Jayred 300 gold!"))
		end)

		it("sends several players who didn't roll to a new losers' tiebreaker", function()
			play("HiLo", { "Jayred", "Piyu", "Zed", "Kal" }, { "Jayred", 400, "Piyu", 100, "Zed", 100, "Kal", 100 })
			game:roll("Piyu", 300)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Tied for last for not rolling: Kal, Zed"))
			assert.are.same({ "Kal", "Zed" }, game:joined_players())

			game:roll("Kal", 50)
			game:roll("Zed", 20)
			assert.is_true(game:chat_contains("Zed owes Jayred 300 gold!"))
		end)
	end)

	describe("in a winners' tiebreaker", function()
		it("makes the player who didn't roll give up the win", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 400, "Piyu", 400, "Zed", 100 })
			game:roll("Jayred", 50)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Gave up the win for not rolling: Piyu"))
			assert.is_true(game:chat_contains("Zed owes Jayred 300 gold!"))
		end)

		it("lets the players who rolled settle it when more than one did", function()
			play("HiLo", { "Jayred", "Piyu", "Kal", "Zed" }, { "Jayred", 400, "Piyu", 400, "Kal", 400, "Zed", 100 })
			game:roll("Jayred", 20)
			game:roll("Piyu", 50)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Gave up the win for not rolling: Kal"))
			assert.is_true(game:chat_contains("Zed owes Piyu 300 gold!"))
		end)

		it("cancels the round when nobody rolled", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 400, "Piyu", 400, "Zed", 100 })
			game:wait_for_timeout()
			assert_cancelled()
		end)
	end)

	describe("when everyone tied", function()
		it("makes the player who didn't roll give up the win and lose", function()
			play("Big2s", { "Jayred", "Piyu", "Zed" }, { "Jayred", 2, "Piyu", 2, "Zed", 2 })
			game:roll("Jayred", 2)
			game:roll("Piyu", 1)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Zed didn't roll and loses the round."))
			assert.is_true(game:chat_contains("Zed owes Jayred 500 gold!"))
		end)

		it("sends several players who didn't roll to a losers' tiebreaker", function()
			play("Big2s", { "Jayred", "Piyu", "Zed", "Kal" }, { "Jayred", 2, "Piyu", 2, "Zed", 2, "Kal", 2 })
			game:roll("Jayred", 2)
			game:roll("Piyu", 1)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Tied for last for not rolling: Kal, Zed"))
			assert.is_true(game:chat_contains("The Losers! Low Tiebreaker:"))

			game:roll("Kal", 2)
			game:roll("Zed", 1)
			assert.is_true(game:chat_contains("Zed owes Jayred 500 gold!"))
		end)

		it("cancels the round when nobody rolled", function()
			play("Big2s", { "Jayred", "Piyu" }, { "Jayred", 2, "Piyu", 2 })
			game:wait_for_timeout()
			assert_cancelled()
		end)

		it("in HiLo, removes the player who didn't roll instead, like a normal round", function()
			play("HiLo", { "Jayred", "Piyu", "Zed" }, { "Jayred", 250, "Piyu", 250, "Zed", 250 })
			game:roll("Jayred", 400)
			game:roll("Piyu", 100)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Removed for not rolling: Zed"))
			assert.is_true(game:chat_contains("Piyu owes Jayred "))
			assert.is_nil(game:rankings().Zed)
		end)

		it("in Inverse, removes the player who didn't roll instead, like a normal round", function()
			play("Inverse", { "Jayred", "Piyu", "Zed" }, { "Jayred", 250, "Piyu", 250, "Zed", 250 })
			game:roll("Jayred", 100)
			game:roll("Piyu", 400)
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Removed for not rolling: Zed"))
			assert.is_true(game:chat_contains("Piyu owes Jayred "))
			assert.is_nil(game:rankings().Zed)
		end)
	end)

	describe("in Countdown", function()
		it("makes the player who didn't roll the roll-off lose", function()
			play("Countdown", { "Jayred", "Piyu" }, { "Jayred", 70 })
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Piyu didn't roll and loses the round."))
			assert.is_true(game:chat_contains("Piyu owes Jayred 500 gold!"))
		end)

		it("cancels the round when neither player rolled the roll-off", function()
			play("Countdown", { "Jayred", "Piyu" })
			game:wait_for_timeout()
			assert_cancelled()
		end)

		it("makes the player who doesn't take their turn lose", function()
			play("Countdown", { "Jayred", "Piyu" }, { "Jayred", 70, "Piyu", 30 })
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Jayred didn't roll and loses the round."))
			assert.is_true(game:chat_contains("Jayred owes Piyu 500 gold!"))
		end)
	end)

	describe("in Blackjack's hit or stand phase", function()
		it("stands players who haven't finished on their current total", function()
			play("Blackjack", { "Jayred", "Piyu" }, { "Jayred", 15, "Piyu", 18 })
			game:say("Jayred", "hit")
			game:wait_for_timeout()
			assert.is_true(game:chat_contains("Time's up! Standing automatically: Jayred, Piyu"))
			assert.is_true(game:chat_contains("Jayred owes Piyu 500 gold!"))
		end)
	end)
end)
